Repository cometbft/cometbft-docs, pull requests merged in 2023-03, with the labels that each got.

#53 fix logic for RPC nav link to remove duplicates
  _includes/nav.html
Labels: bug, ui

#55 Prepare for v0.37.0 release
  VERSIONS
Labels: release

#52 added information about content updates
  README.md
Labels: documentation
